source "https://rubygems.org"

# Declare your gem's dependencies in cms.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem 'rails', '~>6.0'
# gem 'mysql2'

gem 'sass-rails' #, '~> 4.0.3'
# gem 'compass-rails'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'uglifier' #, '>= 1.3.0'

# gem 'coffee-rails'
gem 'slim'

gem 'turbolinks'
gem 'jquery-turbolinks'

#auth / administration
gem 'rails_admin'
gem 'rails_admin-i18n'
gem 'devise'
#bundle exec rails generate paper_trail:install
#inside rails_admin.br
#config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0
#config.audit_with :paper_trail, 'User', 'Version' # PaperTrail < 3.0.0

#breadcrumbs
gem "crummy" #, "~> 1.8.0"
#gem 'breadcrumbs_on_rails'
#forms / helpers
gem 'friendly_id'
gem 'friendly_id-globalize', github: 'norman/friendly_id-globalize'
gem 'simple_form'
gem 'ckeditor'
gem 'kaminari'
gem 'video_info'

# assets
gem 'carrierwave'
gem 'mini_magick'

#gem 'sunspot_rails'
#bundle exec rake sunspot:solr:start | stop

# application-wide configuration
gem 'global'
gem 'xml-sitemap'
gem 'globalize' #, '~> 4.0.2'
#gem 'carmen-rails'
gem 'nested_form'
gem "ransack"
gem "select2-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
